# Datos de planteles - generado automaticamente
WC_PLANTELES = {
    "Argentina": [
        {"nombre": "Emiliano Martinez", "posicion": "GK", "club": "Aston Villa", "valor_m": 30, "edad": 33},
        {"nombre": "Geronimo Rulli", "posicion": "GK", "club": "Olympique Marseille", "valor_m": 8, "edad": 32},
        {"nombre": "Juan Musso", "posicion": "GK", "club": "Atletico Madrid", "valor_m": 12, "edad": 30},
        {"nombre": "Nahuel Molina", "posicion": "DF", "club": "Atletico Madrid", "valor_m": 30, "edad": 26},
        {"nombre": "Cristian Romero", "posicion": "DF", "club": "Tottenham", "valor_m": 65, "edad": 26},
        {"nombre": "Lisandro Martinez", "posicion": "DF", "club": "Manchester United", "valor_m": 55, "edad": 26},
        {"nombre": "Nicolas Otamendi", "posicion": "DF", "club": "Benfica", "valor_m": 10, "edad": 36},
        {"nombre": "Leonardo Balerdi", "posicion": "DF", "club": "Olympique Marseille", "valor_m": 25, "edad": 25},
        {"nombre": "Nicolas Tagliafico", "posicion": "DF", "club": "Olympique Lyon", "valor_m": 8, "edad": 32},
        {"nombre": "Gonzalo Montiel", "posicion": "DF", "club": "River Plate", "valor_m": 10, "edad": 27},
        {"nombre": "Facundo Medina", "posicion": "DF", "club": "Olympique Marseille", "valor_m": 20, "edad": 25},
        {"nombre": "Rodrigo De Paul", "posicion": "MF", "club": "Inter Miami", "valor_m": 25, "edad": 30},
        {"nombre": "Leandro Paredes", "posicion": "MF", "club": "Boca Juniors", "valor_m": 10, "edad": 30},
        {"nombre": "Alexis Mac Allister", "posicion": "MF", "club": "Liverpool", "valor_m": 70, "edad": 25},
        {"nombre": "Enzo Fernandez", "posicion": "MF", "club": "Chelsea", "valor_m": 80, "edad": 23},
        {"nombre": "Exequiel Palacios", "posicion": "MF", "club": "Bayer Leverkusen", "valor_m": 30, "edad": 25},
        {"nombre": "Giovani Lo Celso", "posicion": "MF", "club": "Real Betis", "valor_m": 20, "edad": 28},
        {"nombre": "Valentin Barco", "posicion": "MF", "club": "RC Strasbourg", "valor_m": 15, "edad": 20},
        {"nombre": "Lionel Messi", "posicion": "FW", "club": "Inter Miami", "valor_m": 25, "edad": 37},
        {"nombre": "Lautaro Martinez", "posicion": "FW", "club": "Inter Milan", "valor_m": 100, "edad": 27},
        {"nombre": "Julian Alvarez", "posicion": "FW", "club": "Atletico Madrid", "valor_m": 90, "edad": 24},
        {"nombre": "Nico Gonzalez", "posicion": "FW", "club": "Atletico Madrid", "valor_m": 40, "edad": 26},
        {"nombre": "Thiago Almada", "posicion": "FW", "club": "Atletico Madrid", "valor_m": 35, "edad": 23},
        {"nombre": "Giuliano Simeone", "posicion": "FW", "club": "Atletico Madrid", "valor_m": 25, "edad": 21},
        {"nombre": "Nico Paz", "posicion": "FW", "club": "Como", "valor_m": 30, "edad": 20},
        {"nombre": "Jose Lopez", "posicion": "FW", "club": "Palmeiras", "valor_m": 15, "edad": 23},
    ],
    "Brazil": [
        {"nombre": "Alisson", "posicion": "GK", "club": "Liverpool", "valor_m": 40, "edad": 31},
        {"nombre": "Ederson", "posicion": "GK", "club": "Fenerbahce", "valor_m": 25, "edad": 30},
        {"nombre": "Weverton", "posicion": "GK", "club": "Gremio", "valor_m": 5, "edad": 36},
        {"nombre": "Marquinhos", "posicion": "DF", "club": "PSG", "valor_m": 35, "edad": 29},
        {"nombre": "Gabriel Magalhaes", "posicion": "DF", "club": "Arsenal", "valor_m": 60, "edad": 26},
        {"nombre": "Bremer", "posicion": "DF", "club": "Juventus", "valor_m": 45, "edad": 27},
        {"nombre": "Danilo", "posicion": "DF", "club": "Flamengo", "valor_m": 8, "edad": 33},
        {"nombre": "Alex Sandro", "posicion": "DF", "club": "Flamengo", "valor_m": 3, "edad": 33},
        {"nombre": "Wesley", "posicion": "DF", "club": "AS Roma", "valor_m": 25, "edad": 20},
        {"nombre": "Leo Pereira", "posicion": "DF", "club": "Flamengo", "valor_m": 15, "edad": 28},
        {"nombre": "Roger Ibanez", "posicion": "DF", "club": "Al Ahli", "valor_m": 10, "edad": 25},
        {"nombre": "Douglas Santos", "posicion": "DF", "club": "Zenit", "valor_m": 5, "edad": 30},
        {"nombre": "Bruno Guimaraes", "posicion": "MF", "club": "Newcastle", "valor_m": 80, "edad": 26},
        {"nombre": "Lucas Paqueta", "posicion": "MF", "club": "Flamengo", "valor_m": 45, "edad": 26},
        {"nombre": "Casemiro", "posicion": "MF", "club": "Manchester United", "valor_m": 20, "edad": 32},
        {"nombre": "Fabinho", "posicion": "MF", "club": "Al Ittihad", "valor_m": 12, "edad": 30},
        {"nombre": "Danilo Santos", "posicion": "MF", "club": "Botafogo", "valor_m": 20, "edad": 23},
        {"nombre": "Vinicius Junior", "posicion": "FW", "club": "Real Madrid", "valor_m": 180, "edad": 23},
        {"nombre": "Raphinha", "posicion": "FW", "club": "Barcelona", "valor_m": 80, "edad": 27},
        {"nombre": "Neymar", "posicion": "FW", "club": "Santos", "valor_m": 15, "edad": 32},
        {"nombre": "Gabriel Martinelli", "posicion": "FW", "club": "Arsenal", "valor_m": 70, "edad": 22},
        {"nombre": "Matheus Cunha", "posicion": "FW", "club": "Manchester United", "valor_m": 55, "edad": 25},
        {"nombre": "Endrick", "posicion": "FW", "club": "Olympique Lyon", "valor_m": 60, "edad": 18},
        {"nombre": "Luiz Henrique", "posicion": "FW", "club": "Zenit", "valor_m": 20, "edad": 23},
        {"nombre": "Igor Thiago", "posicion": "FW", "club": "Brentford", "valor_m": 25, "edad": 23},
        {"nombre": "Rayan", "posicion": "FW", "club": "Bournemouth", "valor_m": 15, "edad": 18},
    ],
    "France": [
        {"nombre": "Mike Maignan", "posicion": "GK", "club": "AC Milan", "valor_m": 40, "edad": 28},
        {"nombre": "Brice Samba", "posicion": "GK", "club": "Stade Rennais", "valor_m": 10, "edad": 30},
        {"nombre": "Robin Risser", "posicion": "GK", "club": "RC Lens", "valor_m": 5, "edad": 21},
        {"nombre": "William Saliba", "posicion": "DF", "club": "Arsenal", "valor_m": 80, "edad": 23},
        {"nombre": "Jules Kounde", "posicion": "DF", "club": "Barcelona", "valor_m": 65, "edad": 25},
        {"nombre": "Dayot Upamecano", "posicion": "DF", "club": "Bayern Munich", "valor_m": 50, "edad": 26},
        {"nombre": "Ibrahima Konate", "posicion": "DF", "club": "Liverpool", "valor_m": 55, "edad": 25},
        {"nombre": "Theo Hernandez", "posicion": "DF", "club": "Al Hilal", "valor_m": 40, "edad": 26},
        {"nombre": "Lucas Hernandez", "posicion": "DF", "club": "PSG", "valor_m": 25, "edad": 28},
        {"nombre": "Malo Gusto", "posicion": "DF", "club": "Chelsea", "valor_m": 30, "edad": 21},
        {"nombre": "Lucas Digne", "posicion": "DF", "club": "Aston Villa", "valor_m": 12, "edad": 31},
        {"nombre": "Maxence Lacroix", "posicion": "DF", "club": "Crystal Palace", "valor_m": 20, "edad": 24},
        {"nombre": "Aurelien Tchouameni", "posicion": "MF", "club": "Real Madrid", "valor_m": 80, "edad": 24},
        {"nombre": "NGolo Kante", "posicion": "MF", "club": "Fenerbahce", "valor_m": 20, "edad": 33},
        {"nombre": "Adrien Rabiot", "posicion": "MF", "club": "AC Milan", "valor_m": 20, "edad": 29},
        {"nombre": "Warren Zaire-Emery", "posicion": "MF", "club": "PSG", "valor_m": 60, "edad": 18},
        {"nombre": "Manu Kone", "posicion": "MF", "club": "AS Roma", "valor_m": 35, "edad": 23},
        {"nombre": "Rayan Cherki", "posicion": "MF", "club": "Manchester City", "valor_m": 50, "edad": 21},
        {"nombre": "Maghnes Akliouche", "posicion": "MF", "club": "Monaco", "valor_m": 30, "edad": 22},
        {"nombre": "Kylian Mbappe", "posicion": "FW", "club": "Real Madrid", "valor_m": 180, "edad": 25},
        {"nombre": "Ousmane Dembele", "posicion": "FW", "club": "PSG", "valor_m": 70, "edad": 27},
        {"nombre": "Marcus Thuram", "posicion": "FW", "club": "Inter Milan", "valor_m": 65, "edad": 26},
        {"nombre": "Michael Olise", "posicion": "FW", "club": "Bayern Munich", "valor_m": 70, "edad": 22},
        {"nombre": "Bradley Barcola", "posicion": "FW", "club": "PSG", "valor_m": 60, "edad": 22},
        {"nombre": "Desire Doue", "posicion": "FW", "club": "PSG", "valor_m": 50, "edad": 19},
        {"nombre": "Jean-Philippe Mateta", "posicion": "FW", "club": "Crystal Palace", "valor_m": 30, "edad": 26},
    ],
    "Spain": [
        {"nombre": "Unai Simon", "posicion": "GK", "club": "Athletic Bilbao", "valor_m": 25, "edad": 27},
        {"nombre": "David Raya", "posicion": "GK", "club": "Arsenal", "valor_m": 30, "edad": 29},
        {"nombre": "Alex Remiro", "posicion": "GK", "club": "Real Sociedad", "valor_m": 20, "edad": 29},
        {"nombre": "Dani Carvajal", "posicion": "DF", "club": "Real Madrid", "valor_m": 30, "edad": 32},
        {"nombre": "Aymeric Laporte", "posicion": "DF", "club": "Al Nassr", "valor_m": 15, "edad": 30},
        {"nombre": "Robin Le Normand", "posicion": "DF", "club": "Atletico Madrid", "valor_m": 35, "edad": 27},
        {"nombre": "Pau Cubarsi", "posicion": "DF", "club": "Barcelona", "valor_m": 60, "edad": 17},
        {"nombre": "Marc Cucurella", "posicion": "DF", "club": "Chelsea", "valor_m": 30, "edad": 25},
        {"nombre": "Alejandro Grimaldo", "posicion": "DF", "club": "Bayer Leverkusen", "valor_m": 40, "edad": 28},
        {"nombre": "Rodri", "posicion": "MF", "club": "Manchester City", "valor_m": 120, "edad": 28},
        {"nombre": "Fabian Ruiz", "posicion": "MF", "club": "PSG", "valor_m": 40, "edad": 28},
        {"nombre": "Mikel Merino", "posicion": "MF", "club": "Arsenal", "valor_m": 45, "edad": 28},
        {"nombre": "Martin Zubimendi", "posicion": "MF", "club": "Arsenal", "valor_m": 60, "edad": 25},
        {"nombre": "Dani Olmo", "posicion": "MF", "club": "Barcelona", "valor_m": 65, "edad": 26},
        {"nombre": "Lamine Yamal", "posicion": "FW", "club": "Barcelona", "valor_m": 150, "edad": 16},
        {"nombre": "Nico Williams", "posicion": "FW", "club": "Athletic Bilbao", "valor_m": 80, "edad": 21},
        {"nombre": "Alvaro Morata", "posicion": "FW", "club": "AC Milan", "valor_m": 25, "edad": 31},
        {"nombre": "Joselu", "posicion": "FW", "club": "Real Madrid", "valor_m": 10, "edad": 34},
        {"nombre": "Bryan Gil", "posicion": "FW", "club": "Villarreal", "valor_m": 20, "edad": 23},
    ],
    "England": [
        {"nombre": "Jordan Pickford", "posicion": "GK", "club": "Everton", "valor_m": 20, "edad": 30},
        {"nombre": "Dean Henderson", "posicion": "GK", "club": "Crystal Palace", "valor_m": 12, "edad": 27},
        {"nombre": "James Trafford", "posicion": "GK", "club": "Manchester City", "valor_m": 15, "edad": 21},
        {"nombre": "Reece James", "posicion": "DF", "club": "Chelsea", "valor_m": 50, "edad": 24},
        {"nombre": "John Stones", "posicion": "DF", "club": "Manchester City", "valor_m": 35, "edad": 29},
        {"nombre": "Marc Guehi", "posicion": "DF", "club": "Manchester City", "valor_m": 55, "edad": 24},
        {"nombre": "Ezri Konsa", "posicion": "DF", "club": "Aston Villa", "valor_m": 40, "edad": 26},
        {"nombre": "Tino Livramento", "posicion": "DF", "club": "Newcastle", "valor_m": 30, "edad": 21},
        {"nombre": "Dan Burn", "posicion": "DF", "club": "Newcastle", "valor_m": 10, "edad": 31},
        {"nombre": "Nico OReilly", "posicion": "DF", "club": "Manchester City", "valor_m": 20, "edad": 19},
        {"nombre": "Djed Spence", "posicion": "DF", "club": "Tottenham", "valor_m": 15, "edad": 23},
        {"nombre": "Jarell Quansah", "posicion": "DF", "club": "Bayer Leverkusen", "valor_m": 25, "edad": 21},
        {"nombre": "Declan Rice", "posicion": "MF", "club": "Arsenal", "valor_m": 90, "edad": 25},
        {"nombre": "Jude Bellingham", "posicion": "MF", "club": "Real Madrid", "valor_m": 180, "edad": 20},
        {"nombre": "Kobbie Mainoo", "posicion": "MF", "club": "Manchester United", "valor_m": 60, "edad": 19},
        {"nombre": "Morgan Rogers", "posicion": "MF", "club": "Aston Villa", "valor_m": 40, "edad": 21},
        {"nombre": "Elliot Anderson", "posicion": "MF", "club": "Nottingham Forest", "valor_m": 25, "edad": 21},
        {"nombre": "Jordan Henderson", "posicion": "MF", "club": "Brentford", "valor_m": 5, "edad": 33},
        {"nombre": "Eberechi Eze", "posicion": "MF", "club": "Arsenal", "valor_m": 60, "edad": 26},
        {"nombre": "Harry Kane", "posicion": "FW", "club": "Bayern Munich", "valor_m": 90, "edad": 30},
        {"nombre": "Bukayo Saka", "posicion": "FW", "club": "Arsenal", "valor_m": 150, "edad": 22},
        {"nombre": "Marcus Rashford", "posicion": "FW", "club": "Barcelona", "valor_m": 50, "edad": 26},
        {"nombre": "Ollie Watkins", "posicion": "FW", "club": "Aston Villa", "valor_m": 65, "edad": 28},
        {"nombre": "Anthony Gordon", "posicion": "FW", "club": "Newcastle", "valor_m": 60, "edad": 23},
        {"nombre": "Noni Madueke", "posicion": "FW", "club": "Arsenal", "valor_m": 45, "edad": 22},
        {"nombre": "Ivan Toney", "posicion": "FW", "club": "Al Ahli", "valor_m": 35, "edad": 28},
    ],
    "Germany": [
        {"nombre": "Manuel Neuer", "posicion": "GK", "club": "Bayern Munich", "valor_m": 10, "edad": 38},
        {"nombre": "Oliver Baumann", "posicion": "GK", "club": "Hoffenheim", "valor_m": 5, "edad": 33},
        {"nombre": "Alexander Nubel", "posicion": "GK", "club": "VfB Stuttgart", "valor_m": 15, "edad": 27},
        {"nombre": "Antonio Rudiger", "posicion": "DF", "club": "Real Madrid", "valor_m": 25, "edad": 31},
        {"nombre": "Jonathan Tah", "posicion": "DF", "club": "Bayern Munich", "valor_m": 35, "edad": 28},
        {"nombre": "Nico Schlotterbeck", "posicion": "DF", "club": "Borussia Dortmund", "valor_m": 35, "edad": 24},
        {"nombre": "Joshua Kimmich", "posicion": "DF", "club": "Bayern Munich", "valor_m": 60, "edad": 29},
        {"nombre": "Waldemar Anton", "posicion": "DF", "club": "Borussia Dortmund", "valor_m": 20, "edad": 27},
        {"nombre": "David Raum", "posicion": "DF", "club": "RB Leipzig", "valor_m": 25, "edad": 26},
        {"nombre": "Nathaniel Brown", "posicion": "DF", "club": "Eintracht Frankfurt", "valor_m": 15, "edad": 21},
        {"nombre": "Malick Thiaw", "posicion": "DF", "club": "Newcastle", "valor_m": 30, "edad": 22},
        {"nombre": "Florian Wirtz", "posicion": "MF", "club": "Liverpool", "valor_m": 150, "edad": 21},
        {"nombre": "Jamal Musiala", "posicion": "MF", "club": "Bayern Munich", "valor_m": 130, "edad": 21},
        {"nombre": "Leon Goretzka", "posicion": "MF", "club": "Bayern Munich", "valor_m": 30, "edad": 29},
        {"nombre": "Aleksandar Pavlovic", "posicion": "MF", "club": "Bayern Munich", "valor_m": 40, "edad": 20},
        {"nombre": "Angelo Stiller", "posicion": "MF", "club": "VfB Stuttgart", "valor_m": 30, "edad": 23},
        {"nombre": "Pascal Gross", "posicion": "MF", "club": "Brighton", "valor_m": 15, "edad": 32},
        {"nombre": "Nadiem Amiri", "posicion": "MF", "club": "Mainz", "valor_m": 8, "edad": 27},
        {"nombre": "Felix Nmecha", "posicion": "MF", "club": "Borussia Dortmund", "valor_m": 25, "edad": 23},
        {"nombre": "Lennart Karl", "posicion": "MF", "club": "Bayern Munich", "valor_m": 8, "edad": 16},
        {"nombre": "Kai Havertz", "posicion": "FW", "club": "Arsenal", "valor_m": 65, "edad": 25},
        {"nombre": "Leroy Sane", "posicion": "FW", "club": "Galatasaray", "valor_m": 30, "edad": 28},
        {"nombre": "Maximilian Beier", "posicion": "FW", "club": "Borussia Dortmund", "valor_m": 35, "edad": 21},
        {"nombre": "Nick Woltemade", "posicion": "FW", "club": "Newcastle", "valor_m": 20, "edad": 22},
        {"nombre": "Jamie Leweling", "posicion": "FW", "club": "VfB Stuttgart", "valor_m": 20, "edad": 23},
        {"nombre": "Deniz Undav", "posicion": "FW", "club": "VfB Stuttgart", "valor_m": 25, "edad": 27},
    ],
    "Portugal": [
        {"nombre": "Diogo Costa", "posicion": "GK", "club": "FC Porto", "valor_m": 35, "edad": 24},
        {"nombre": "Jose Sa", "posicion": "GK", "club": "Wolverhampton", "valor_m": 15, "edad": 31},
        {"nombre": "Rui Silva", "posicion": "GK", "club": "Sporting CP", "valor_m": 8, "edad": 30},
        {"nombre": "Ruben Dias", "posicion": "DF", "club": "Manchester City", "valor_m": 80, "edad": 27},
        {"nombre": "Joao Cancelo", "posicion": "DF", "club": "Barcelona", "valor_m": 30, "edad": 30},
        {"nombre": "Nelson Semedo", "posicion": "DF", "club": "Fenerbahce", "valor_m": 15, "edad": 30},
        {"nombre": "Diogo Dalot", "posicion": "DF", "club": "Manchester United", "valor_m": 35, "edad": 25},
        {"nombre": "Nuno Mendes", "posicion": "DF", "club": "PSG", "valor_m": 60, "edad": 22},
        {"nombre": "Goncalo Inacio", "posicion": "DF", "club": "Sporting CP", "valor_m": 45, "edad": 22},
        {"nombre": "Tomas Araujo", "posicion": "DF", "club": "Benfica", "valor_m": 30, "edad": 22},
        {"nombre": "Renato Veiga", "posicion": "DF", "club": "Villarreal", "valor_m": 25, "edad": 21},
        {"nombre": "Samu Costa", "posicion": "DF", "club": "Mallorca", "valor_m": 15, "edad": 23},
        {"nombre": "Bruno Fernandes", "posicion": "MF", "club": "Manchester United", "valor_m": 70, "edad": 29},
        {"nombre": "Bernardo Silva", "posicion": "MF", "club": "Manchester City", "valor_m": 80, "edad": 29},
        {"nombre": "Vitinha", "posicion": "MF", "club": "PSG", "valor_m": 60, "edad": 24},
        {"nombre": "Joao Neves", "posicion": "MF", "club": "PSG", "valor_m": 80, "edad": 19},
        {"nombre": "Matheus Nunes", "posicion": "MF", "club": "Manchester City", "valor_m": 45, "edad": 25},
        {"nombre": "Ruben Neves", "posicion": "MF", "club": "Al Hilal", "valor_m": 20, "edad": 27},
        {"nombre": "Cristiano Ronaldo", "posicion": "FW", "club": "Al Nassr", "valor_m": 15, "edad": 39},
        {"nombre": "Rafael Leao", "posicion": "FW", "club": "AC Milan", "valor_m": 80, "edad": 24},
        {"nombre": "Goncalo Ramos", "posicion": "FW", "club": "PSG", "valor_m": 55, "edad": 23},
        {"nombre": "Joao Felix", "posicion": "FW", "club": "Al Nassr", "valor_m": 35, "edad": 24},
        {"nombre": "Pedro Neto", "posicion": "FW", "club": "Chelsea", "valor_m": 55, "edad": 24},
        {"nombre": "Francisco Trincao", "posicion": "FW", "club": "Sporting CP", "valor_m": 25, "edad": 24},
        {"nombre": "Goncalo Guedes", "posicion": "FW", "club": "Real Sociedad", "valor_m": 20, "edad": 27},
        {"nombre": "Francisco Conceicao", "posicion": "FW", "club": "Juventus", "valor_m": 35, "edad": 21},
    ],
    "Netherlands": [
        {"nombre": "Bart Verbruggen", "posicion": "GK", "club": "Brighton", "valor_m": 25, "edad": 21},
        {"nombre": "Mark Flekken", "posicion": "GK", "club": "Bayer Leverkusen", "valor_m": 15, "edad": 30},
        {"nombre": "Robin Roefs", "posicion": "GK", "club": "Sunderland", "valor_m": 5, "edad": 21},
        {"nombre": "Virgil van Dijk", "posicion": "DF", "club": "Liverpool", "valor_m": 40, "edad": 32},
        {"nombre": "Jurrien Timber", "posicion": "DF", "club": "Arsenal", "valor_m": 55, "edad": 22},
        {"nombre": "Nathan Ake", "posicion": "DF", "club": "Manchester City", "valor_m": 35, "edad": 29},
        {"nombre": "Jan-Paul van Hecke", "posicion": "DF", "club": "Brighton", "valor_m": 30, "edad": 24},
        {"nombre": "Denzel Dumfries", "posicion": "DF", "club": "Inter Milan", "valor_m": 30, "edad": 28},
        {"nombre": "Micky van de Ven", "posicion": "DF", "club": "Tottenham", "valor_m": 50, "edad": 23},
        {"nombre": "Mats Wieffer", "posicion": "DF", "club": "Brighton", "valor_m": 30, "edad": 24},
        {"nombre": "Jorrel Hato", "posicion": "DF", "club": "Chelsea", "valor_m": 25, "edad": 18},
        {"nombre": "Frenkie de Jong", "posicion": "MF", "club": "Barcelona", "valor_m": 60, "edad": 27},
        {"nombre": "Ryan Gravenberch", "posicion": "MF", "club": "Liverpool", "valor_m": 60, "edad": 22},
        {"nombre": "Tijjani Reijnders", "posicion": "MF", "club": "Manchester City", "valor_m": 55, "edad": 26},
        {"nombre": "Marten de Roon", "posicion": "MF", "club": "Atalanta", "valor_m": 15, "edad": 33},
        {"nombre": "Teun Koopmeiners", "posicion": "MF", "club": "Juventus", "valor_m": 60, "edad": 26},
        {"nombre": "Guus Til", "posicion": "MF", "club": "PSV Eindhoven", "valor_m": 20, "edad": 26},
        {"nombre": "Quinten Timber", "posicion": "MF", "club": "Olympique Marseille", "valor_m": 20, "edad": 22},
        {"nombre": "Cody Gakpo", "posicion": "FW", "club": "Liverpool", "valor_m": 65, "edad": 25},
        {"nombre": "Memphis Depay", "posicion": "FW", "club": "Corinthians", "valor_m": 10, "edad": 30},
        {"nombre": "Wout Weghorst", "posicion": "FW", "club": "Ajax", "valor_m": 12, "edad": 31},
        {"nombre": "Donyell Malen", "posicion": "FW", "club": "AS Roma", "valor_m": 30, "edad": 25},
        {"nombre": "Noa Lang", "posicion": "FW", "club": "Galatasaray", "valor_m": 25, "edad": 25},
        {"nombre": "Brian Brobbey", "posicion": "FW", "club": "Sunderland", "valor_m": 30, "edad": 23},
        {"nombre": "Justin Kluivert", "posicion": "FW", "club": "Bournemouth", "valor_m": 20, "edad": 25},
        {"nombre": "Crysencio Summerville", "posicion": "FW", "club": "West Ham", "valor_m": 35, "edad": 22},
    ],
    "Belgium": [
        {"nombre": "Thibaut Courtois", "posicion": "GK", "club": "Real Madrid", "valor_m": 30, "edad": 32},
        {"nombre": "Senne Lammens", "posicion": "GK", "club": "Manchester United", "valor_m": 8, "edad": 22},
        {"nombre": "Mike Penders", "posicion": "GK", "club": "RC Strasbourg", "valor_m": 5, "edad": 19},
        {"nombre": "Zeno Debast", "posicion": "DF", "club": "Sporting CP", "valor_m": 30, "edad": 21},
        {"nombre": "Arthur Theate", "posicion": "DF", "club": "Eintracht Frankfurt", "valor_m": 25, "edad": 24},
        {"nombre": "Brandon Mechele", "posicion": "DF", "club": "Club Brugge", "valor_m": 8, "edad": 31},
        {"nombre": "Maxim De Cuyper", "posicion": "DF", "club": "Brighton", "valor_m": 25, "edad": 23},
        {"nombre": "Thomas Meunier", "posicion": "DF", "club": "Lille", "valor_m": 8, "edad": 32},
        {"nombre": "Koni De Winter", "posicion": "DF", "club": "AC Milan", "valor_m": 20, "edad": 22},
        {"nombre": "Timothy Castagne", "posicion": "DF", "club": "Fulham", "valor_m": 15, "edad": 28},
        {"nombre": "Joaquin Seys", "posicion": "DF", "club": "Club Brugge", "valor_m": 8, "edad": 19},
        {"nombre": "Nathan Ngoy", "posicion": "DF", "club": "Lille", "valor_m": 5, "edad": 21},
        {"nombre": "Kevin De Bruyne", "posicion": "MF", "club": "Napoli", "valor_m": 50, "edad": 33},
        {"nombre": "Youri Tielemans", "posicion": "MF", "club": "Aston Villa", "valor_m": 30, "edad": 27},
        {"nombre": "Axel Witsel", "posicion": "MF", "club": "Girona", "valor_m": 5, "edad": 35},
        {"nombre": "Amadou Onana", "posicion": "MF", "club": "Aston Villa", "valor_m": 55, "edad": 23},
        {"nombre": "Hans Vanaken", "posicion": "MF", "club": "Club Brugge", "valor_m": 10, "edad": 31},
        {"nombre": "Alexis Saelemaekers", "posicion": "MF", "club": "AC Milan", "valor_m": 20, "edad": 25},
        {"nombre": "Nicolas Raskin", "posicion": "MF", "club": "Rangers", "valor_m": 15, "edad": 23},
        {"nombre": "Diego Moreira", "posicion": "MF", "club": "RC Strasbourg", "valor_m": 12, "edad": 20},
        {"nombre": "Romelu Lukaku", "posicion": "FW", "club": "Napoli", "valor_m": 25, "edad": 31},
        {"nombre": "Leandro Trossard", "posicion": "FW", "club": "Arsenal", "valor_m": 30, "edad": 29},
        {"nombre": "Jeremy Doku", "posicion": "FW", "club": "Manchester City", "valor_m": 60, "edad": 22},
        {"nombre": "Dodi Lukebakio", "posicion": "FW", "club": "Benfica", "valor_m": 20, "edad": 26},
        {"nombre": "Charles De Ketelaere", "posicion": "FW", "club": "Atalanta", "valor_m": 40, "edad": 23},
        {"nombre": "Matias Fernandez-Pardo", "posicion": "FW", "club": "Lille", "valor_m": 15, "edad": 19},
    ],
    "Croatia": [
        {"nombre": "Dominik Livakovic", "posicion": "GK", "club": "Dinamo Zagreb", "valor_m": 18, "edad": 29},
        {"nombre": "Ivor Pandur", "posicion": "GK", "club": "Hull City", "valor_m": 5, "edad": 24},
        {"nombre": "Dominik Kotarski", "posicion": "GK", "club": "FC Kobenhavn", "valor_m": 8, "edad": 24},
        {"nombre": "Josko Gvardiol", "posicion": "DF", "club": "Manchester City", "valor_m": 80, "edad": 22},
        {"nombre": "Josip Stanisic", "posicion": "DF", "club": "Bayern Munich", "valor_m": 20, "edad": 24},
        {"nombre": "Marin Pongracic", "posicion": "DF", "club": "Fiorentina", "valor_m": 20, "edad": 26},
        {"nombre": "Duje Caleta-Car", "posicion": "DF", "club": "Real Sociedad", "valor_m": 15, "edad": 27},
        {"nombre": "Josip Sutalo", "posicion": "DF", "club": "Ajax", "valor_m": 20, "edad": 24},
        {"nombre": "Kristijan Jakic", "posicion": "DF", "club": "Augsburg", "valor_m": 10, "edad": 27},
        {"nombre": "Martin Erlic", "posicion": "DF", "club": "Midtjylland", "valor_m": 8, "edad": 26},
        {"nombre": "Luka Vuskovic", "posicion": "DF", "club": "Hamburger SV", "valor_m": 15, "edad": 17},
        {"nombre": "Luka Modric", "posicion": "MF", "club": "AC Milan", "valor_m": 8, "edad": 38},
        {"nombre": "Mateo Kovacic", "posicion": "MF", "club": "Manchester City", "valor_m": 35, "edad": 30},
        {"nombre": "Mario Pasalic", "posicion": "MF", "club": "Atalanta", "valor_m": 25, "edad": 29},
        {"nombre": "Nikola Moro", "posicion": "MF", "club": "Bologna", "valor_m": 12, "edad": 26},
        {"nombre": "Nikola Vlasic", "posicion": "MF", "club": "Torino", "valor_m": 20, "edad": 26},
        {"nombre": "Martin Baturina", "posicion": "MF", "club": "Como", "valor_m": 25, "edad": 21},
        {"nombre": "Petar Sucic", "posicion": "MF", "club": "Inter Milan", "valor_m": 30, "edad": 21},
        {"nombre": "Luka Sucic", "posicion": "MF", "club": "Real Sociedad", "valor_m": 25, "edad": 22},
        {"nombre": "Toni Fruk", "posicion": "MF", "club": "Rijeka", "valor_m": 5, "edad": 23},
        {"nombre": "Andrej Kramaric", "posicion": "FW", "club": "Hoffenheim", "valor_m": 15, "edad": 33},
        {"nombre": "Ante Budimir", "posicion": "FW", "club": "Osasuna", "valor_m": 10, "edad": 33},
        {"nombre": "Ivan Perisic", "posicion": "FW", "club": "PSV Eindhoven", "valor_m": 8, "edad": 35},
        {"nombre": "Igor Matanovic", "posicion": "FW", "club": "Freiburg", "valor_m": 15, "edad": 21},
        {"nombre": "Marco Pasalic", "posicion": "FW", "club": "Orlando City", "valor_m": 5, "edad": 23},
        {"nombre": "Petar Musa", "posicion": "FW", "club": "FC Dallas", "valor_m": 8, "edad": 26},
    ],
    "Uruguay": [
        {"nombre": "Sergio Rochet", "posicion": "GK", "club": "Nacional", "valor_m": 5, "edad": 30},
        {"nombre": "Sebastian Sosa", "posicion": "GK", "club": "Independiente", "valor_m": 3, "edad": 37},
        {"nombre": "Jose Maria Gimenez", "posicion": "DF", "club": "Atletico Madrid", "valor_m": 35, "edad": 29},
        {"nombre": "Sebastian Caceres", "posicion": "DF", "club": "Atlas", "valor_m": 5, "edad": 25},
        {"nombre": "Mathias Olivera", "posicion": "DF", "club": "Napoli", "valor_m": 30, "edad": 26},
        {"nombre": "Manuel Ugarte", "posicion": "MF", "club": "Manchester United", "valor_m": 50, "edad": 23},
        {"nombre": "Rodrigo Bentancur", "posicion": "MF", "club": "Tottenham", "valor_m": 35, "edad": 26},
        {"nombre": "Nicolas De La Cruz", "posicion": "MF", "club": "Flamengo", "valor_m": 20, "edad": 27},
        {"nombre": "Lucas Torreira", "posicion": "MF", "club": "Galatasaray", "valor_m": 15, "edad": 28},
        {"nombre": "Darwin Nunez", "posicion": "FW", "club": "Liverpool", "valor_m": 80, "edad": 24},
        {"nombre": "Luis Suarez", "posicion": "FW", "club": "River Plate", "valor_m": 5, "edad": 37},
        {"nombre": "Facundo Torres", "posicion": "FW", "club": "Orlando City", "valor_m": 15, "edad": 24},
        {"nombre": "Maximiliano Gomez", "posicion": "FW", "club": "Trabzonspor", "valor_m": 8, "edad": 28},
    ],
    "Colombia": [
        {"nombre": "David Ospina", "posicion": "GK", "club": "Atletico Nacional", "valor_m": 5, "edad": 35},
        {"nombre": "Camilo Vargas", "posicion": "GK", "club": "Atlas", "valor_m": 3, "edad": 35},
        {"nombre": "Daniel Munoz", "posicion": "DF", "club": "Crystal Palace", "valor_m": 20, "edad": 28},
        {"nombre": "Jhon Lucumi", "posicion": "DF", "club": "Bologna", "valor_m": 20, "edad": 26},
        {"nombre": "Davinson Sanchez", "posicion": "DF", "club": "Galatasaray", "valor_m": 15, "edad": 27},
        {"nombre": "Richard Rios", "posicion": "MF", "club": "Benfica", "valor_m": 30, "edad": 24},
        {"nombre": "Kevin Castano", "posicion": "MF", "club": "River Plate", "valor_m": 15, "edad": 23},
        {"nombre": "Jefferson Lerma", "posicion": "MF", "club": "Crystal Palace", "valor_m": 15, "edad": 29},
        {"nombre": "Jhon Arias", "posicion": "MF", "club": "Palmeiras", "valor_m": 25, "edad": 26},
        {"nombre": "James Rodriguez", "posicion": "MF", "club": "Minnesota United", "valor_m": 8, "edad": 32},
        {"nombre": "Luis Diaz", "posicion": "FW", "club": "Bayern Munich", "valor_m": 80, "edad": 27},
        {"nombre": "Cucho Hernandez", "posicion": "FW", "club": "Real Betis", "valor_m": 25, "edad": 25},
        {"nombre": "Jhon Cordoba", "posicion": "FW", "club": "Krasnodar", "valor_m": 12, "edad": 31},
    ],
    "Morocco": [
        {"nombre": "Yassine Bounou", "posicion": "GK", "club": "Al Hilal", "valor_m": 15, "edad": 33},
        {"nombre": "Achraf Hakimi", "posicion": "DF", "club": "PSG", "valor_m": 70, "edad": 25},
        {"nombre": "Noussair Mazraoui", "posicion": "DF", "club": "Manchester United", "valor_m": 30, "edad": 26},
        {"nombre": "Nayef Aguerd", "posicion": "DF", "club": "Olympique Marseille", "valor_m": 20, "edad": 28},
        {"nombre": "Sofyan Amrabat", "posicion": "MF", "club": "Real Betis", "valor_m": 20, "edad": 28},
        {"nombre": "Azzedine Ounahi", "posicion": "MF", "club": "Girona", "valor_m": 15, "edad": 24},
        {"nombre": "Ismael Saibari", "posicion": "MF", "club": "PSV Eindhoven", "valor_m": 25, "edad": 23},
        {"nombre": "Bilal El Khannouss", "posicion": "MF", "club": "VfB Stuttgart", "valor_m": 20, "edad": 20},
        {"nombre": "Brahim Diaz", "posicion": "FW", "club": "Real Madrid", "valor_m": 40, "edad": 24},
        {"nombre": "Ayoub El Kaabi", "posicion": "FW", "club": "Olympiakos", "valor_m": 15, "edad": 31},
        {"nombre": "Abde Ezzalzouli", "posicion": "FW", "club": "Real Betis", "valor_m": 20, "edad": 22},
    ],
    "Japan": [
        {"nombre": "Zion Suzuki", "posicion": "GK", "club": "Parma", "valor_m": 10, "edad": 21},
        {"nombre": "Kim Minjae", "posicion": "DF", "club": "Bayern Munich", "valor_m": 50, "edad": 27},
        {"nombre": "Takehiro Tomiyasu", "posicion": "DF", "club": "Ajax", "valor_m": 20, "edad": 25},
        {"nombre": "Kou Itakura", "posicion": "DF", "club": "Ajax", "valor_m": 15, "edad": 27},
        {"nombre": "Hiroki Ito", "posicion": "DF", "club": "Bayern Munich", "valor_m": 25, "edad": 25},
        {"nombre": "Wataru Endo", "posicion": "MF", "club": "Liverpool", "valor_m": 20, "edad": 31},
        {"nombre": "Ao Tanaka", "posicion": "MF", "club": "Leeds United", "valor_m": 15, "edad": 25},
        {"nombre": "Daichi Kamada", "posicion": "MF", "club": "Crystal Palace", "valor_m": 20, "edad": 27},
        {"nombre": "Takefusa Kubo", "posicion": "FW", "club": "Real Sociedad", "valor_m": 50, "edad": 23},
        {"nombre": "Ritsu Doan", "posicion": "FW", "club": "Eintracht Frankfurt", "valor_m": 25, "edad": 26},
        {"nombre": "Daizen Maeda", "posicion": "FW", "club": "Celtic", "valor_m": 15, "edad": 26},
    ],
    "USA": [
        {"nombre": "Matt Turner", "posicion": "GK", "club": "Nottingham Forest", "valor_m": 10, "edad": 29},
        {"nombre": "Sergino Dest", "posicion": "DF", "club": "PSV Eindhoven", "valor_m": 20, "edad": 24},
        {"nombre": "Chris Richards", "posicion": "DF", "club": "Crystal Palace", "valor_m": 15, "edad": 24},
        {"nombre": "Antonee Robinson", "posicion": "DF", "club": "Fulham", "valor_m": 20, "edad": 27},
        {"nombre": "Christian Pulisic", "posicion": "MF", "club": "AC Milan", "valor_m": 50, "edad": 26},
        {"nombre": "Weston McKennie", "posicion": "MF", "club": "Juventus", "valor_m": 20, "edad": 26},
        {"nombre": "Tyler Adams", "posicion": "MF", "club": "Bournemouth", "valor_m": 20, "edad": 25},
        {"nombre": "Yunus Musah", "posicion": "MF", "club": "AC Milan", "valor_m": 25, "edad": 22},
        {"nombre": "Ricardo Pepi", "posicion": "FW", "club": "PSV Eindhoven", "valor_m": 15, "edad": 22},
        {"nombre": "Folarin Balogun", "posicion": "FW", "club": "Monaco", "valor_m": 30, "edad": 23},
        {"nombre": "Timothy Weah", "posicion": "FW", "club": "Juventus", "valor_m": 15, "edad": 24},
    ],
    "Mexico": [
        {"nombre": "Raul Rangel", "posicion": "GK", "club": "Guadalajara", "valor_m": 5, "edad": 24},
        {"nombre": "Edson Alvarez", "posicion": "MF", "club": "Fenerbahce", "valor_m": 30, "edad": 26},
        {"nombre": "Johan Vasquez", "posicion": "DF", "club": "Genoa", "valor_m": 10, "edad": 25},
        {"nombre": "Cesar Montes", "posicion": "DF", "club": "Lokomotiv Moscow", "valor_m": 8, "edad": 27},
        {"nombre": "Obed Vargas", "posicion": "MF", "club": "Atletico Madrid", "valor_m": 15, "edad": 19},
        {"nombre": "Santiago Gimenez", "posicion": "FW", "club": "AC Milan", "valor_m": 45, "edad": 23},
        {"nombre": "Raul Jimenez", "posicion": "FW", "club": "Fulham", "valor_m": 15, "edad": 33},
    ],
    "Ecuador": [
        {"nombre": "Moises Caicedo", "posicion": "MF", "club": "Chelsea", "valor_m": 100, "edad": 22},
        {"nombre": "Piero Hincapie", "posicion": "DF", "club": "Arsenal", "valor_m": 45, "edad": 22},
        {"nombre": "Willian Pacho", "posicion": "DF", "club": "PSG", "valor_m": 40, "edad": 22},
        {"nombre": "Pervis Estupinan", "posicion": "DF", "club": "AC Milan", "valor_m": 35, "edad": 26},
        {"nombre": "Kendry Paez", "posicion": "MF", "club": "River Plate", "valor_m": 25, "edad": 17},
        {"nombre": "Gonzalo Plata", "posicion": "FW", "club": "Flamengo", "valor_m": 20, "edad": 23},
        {"nombre": "Enner Valencia", "posicion": "FW", "club": "Pachuca", "valor_m": 5, "edad": 34},
    ],
    "Canada": [
        {"nombre": "Alphonso Davies", "posicion": "DF", "club": "Bayern Munich", "valor_m": 70, "edad": 23},
        {"nombre": "Jonathan David", "posicion": "FW", "club": "Juventus", "valor_m": 65, "edad": 24},
        {"nombre": "Stephen Eustaquio", "posicion": "MF", "club": "LAFC", "valor_m": 20, "edad": 27},
        {"nombre": "Tajon Buchanan", "posicion": "FW", "club": "Villarreal", "valor_m": 20, "edad": 25},
        {"nombre": "Ismael Kone", "posicion": "MF", "club": "Sassuolo", "valor_m": 20, "edad": 22},
        {"nombre": "Moise Bombito", "posicion": "DF", "club": "Nice", "valor_m": 15, "edad": 24},
    ],
    "Senegal": [
        {"nombre": "Nicolas Jackson", "posicion": "FW", "club": "Bayern Munich", "valor_m": 60, "edad": 23},
        {"nombre": "Pape Matar Sarr", "posicion": "MF", "club": "Tottenham", "valor_m": 35, "edad": 21},
        {"nombre": "Lamine Camara", "posicion": "MF", "club": "Monaco", "valor_m": 35, "edad": 20},
        {"nombre": "Ismaila Sarr", "posicion": "FW", "club": "Crystal Palace", "valor_m": 25, "edad": 26},
        {"nombre": "Iliman Ndiaye", "posicion": "FW", "club": "Everton", "valor_m": 20, "edad": 24},
        {"nombre": "Sadio Mane", "posicion": "FW", "club": "Al Nassr", "valor_m": 10, "edad": 32},
        {"nombre": "Kalidou Koulibaly", "posicion": "DF", "club": "Al Hilal", "valor_m": 15, "edad": 33},
    ],
    "Australia": [
        {"nombre": "Nestory Irankunda", "posicion": "FW", "club": "Watford", "valor_m": 15, "edad": 18},
        {"nombre": "Mathew Ryan", "posicion": "GK", "club": "Levante", "valor_m": 5, "edad": 32},
        {"nombre": "Harry Souttar", "posicion": "DF", "club": "Leicester City", "valor_m": 10, "edad": 25},
        {"nombre": "Cristian Volpato", "posicion": "FW", "club": "Sassuolo", "valor_m": 8, "edad": 21},
        {"nombre": "Jackson Irvine", "posicion": "MF", "club": "St. Pauli", "valor_m": 5, "edad": 31},
    ],
    "South Korea": [
        {"nombre": "Son Heungmin", "posicion": "FW", "club": "LAFC", "valor_m": 25, "edad": 31},
        {"nombre": "Kim Minjae", "posicion": "DF", "club": "Bayern Munich", "valor_m": 50, "edad": 27},
        {"nombre": "Lee Kangin", "posicion": "MF", "club": "PSG", "valor_m": 35, "edad": 23},
        {"nombre": "Hwang Heechan", "posicion": "FW", "club": "Wolverhampton", "valor_m": 20, "edad": 28},
        {"nombre": "Hwang Inbeom", "posicion": "MF", "club": "Feyenoord", "valor_m": 15, "edad": 27},
    ],
    "Saudi Arabia": [
        {"nombre": "Saud Abdulhamid", "posicion": "DF", "club": "RC Lens", "valor_m": 8, "edad": 25},
        {"nombre": "Salem Aldawsari", "posicion": "FW", "club": "Al Hilal", "valor_m": 8, "edad": 33},
        {"nombre": "Akram Afif", "posicion": "FW", "club": "Al Sadd", "valor_m": 10, "edad": 27},
    ],
    "Qatar": [
        {"nombre": "Akram Afif", "posicion": "FW", "club": "Al Sadd", "valor_m": 10, "edad": 27},
        {"nombre": "Almoez Ali", "posicion": "FW", "club": "Al Duhail", "valor_m": 5, "edad": 27},
        {"nombre": "Hassan Alhaydos", "posicion": "FW", "club": "Al Sadd", "valor_m": 5, "edad": 33},
    ],
}
